# -*- coding: utf-8 -*-
"""
/***************************************************************************
 G2S
                                 A QGIS plugin
 Interface G2S
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2019-10-31
        copyright            : (C) 2019 by Mathieu Gravey @ The University of Lausanne
        email                : mathieu.gravey@unil.ch
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Mathieu Gravey @ The University of Lausanne'
__date__ = '2019-10-31'
__copyright__ = '(C) 2019 by Mathieu Gravey @ The University of Lausanne'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load G2S class from file G2S.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .g2s_qgis import G2SPlugin
    return G2SPlugin()
